compute_environment: LOCAL_MACHINE
debug: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: "no"
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
deepspeed_config:
  zero_stage: 3
  zero3_init_flag: true
  zero_optimization:
    stage: 3
    offload_optimizer:
      device: "cpu"
      pin_memory: true
    offload_param:
      device: "cpu"
      pin_memory: true
    overlap_comm: true
    contiguous_gradients: true
    reduce_bucket_size: 5e7
    stage3_prefetch_bucket_size: 5e7
    stage3_param_persistence_threshold: 1e6
    memory_efficient_linear: true
    round_robin_gradients: true
  optimizer: 
    type: "adamw_torch_fused"
  train_batch_size: "auto"
  train_micro_batch_size_per_gpu: "auto"
  gradient_accumulation_steps: 128
  zero_allow_untested_optimizer: true
  gradient_clipping: 1.0
